### DISCUSSION TITLE
Set CROP size in config

### DISCUSSION THREAD

**Discussion by kadattack** [bowenc0221/panoptic-deeplab#81] [Q&A] [answered]
I am new to Detectron2 so forgive me if this is not related to Panoptic-deeplab implementation

I am a bit confused how _C.INPUT.CROP.SIZE for data augmentation works in the config file
https://detectron2.readthedocs.io/en/latest/modules/config.html#config-references
I have my own dataset with images that are all in 512x384 size.
However when I use SIZE: (640, 640) for CROP, it trains and gives ok results without any errors.
I thought the CROP needs to be smaller than the image size?
```
INPUT:
  FORMAT: "RGB"
  GAUSSIAN_SIGMA: 8
  MIN_SIZE_TRAIN: (320, 384, 448, 512)
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 384
  MAX_SIZE_TRAIN: 512
  MAX_SIZE_TEST: 512
  CROP:
    ENABLED: True
    TYPE: "absolute"
    SIZE: (640, 640)
```
