### ISSUE TITLE
is there pretrained model for COCO we can download?

### ISSUE THREAD

**Issue by squashking** [bowenc0221/panoptic-deeplab#4]
Hi Bowen,
Thanks for the code. is there pretrained model for COCO we can download?

**Comment by bowenc0221** [comment]
I'm still trying to reproduce the COCO number, I will release the model once I get a similar result. But COCO is already supported, you can play with it if you like :)

**Comment by lxtGH** [comment]
@bowenc0221 Hi Bowen, Would you share the config files and detialed settings on COCO dataset?

**Comment by bowenc0221** [comment]
Here is part of the config you might need to change. I will upload the config file once I can reproduce a reasonable result.

```
DATASET:
  ROOT: "./datasets/coco"
  DATASET: "coco_panoptic"
  NUM_CLASSES: 133
  TRAIN_SPLIT: 'train2017'
  TEST_SPLIT: 'val2017'
  MIN_RESIZE_VALUE: 641
  MAX_RESIZE_VALUE: 641
  RESIZE_FACTOR: 32
  CROP_SIZE: (641, 641)
  MIRROR: True
  MIN_SCALE: 0.5  # change this
  MAX_SCALE: 1.5  # change this
  SCALE_STEP_SIZE: 0.1
  MEAN: (0.485, 0.456, 0.406)
  STD: (0.229, 0.224, 0.225)
  SEMANTIC_ONLY: False
  IGNORE_STUFF_IN_OFFSET: True
  SMALL_INSTANCE_AREA: 4096
  SMALL_INSTANCE_WEIGHT: 3
LOSS:
  SEMANTIC:
    NAME: "cross_entropy"
    IGNORE: 255
TRAIN:
  IMS_PER_BATCH: 12  # change this
  MAX_ITER: 600000  # change this
TEST:
  CROP_SIZE: (641, 641)
```

Note, the loss function for the semantic branch no longer uses hard pixel mining. Because COCO annotation quality is not good.
