### ISSUE TITLE
Training time detectron2 vs base implementation

### ISSUE THREAD

**Issue by AndraPetrovai** [bowenc0221/panoptic-deeplab#52]
Thank you for this repo! 
I am training the ResNet50-based network on the Cityscapes dataset on 4 V100 GPUs with the following settings:

**base implementation**
config : `configs/panoptic_deeplab_R50_os32_cityscapes.yaml`
with `NUM_WORKERS: 4`

**detectron2 implementation**
config: `configs/Cityscapes-PanopticSegmentation/panoptic_deeplab_R_52_os16_mg124_poly_90k_bs32_crop_512_1024.yaml`
but made the following changes so that I am using the same setup as `configs/panoptic_deeplab_R50_os32_cityscapes.yaml` from the base implementation
```
MIN_SIZE_TRAIN: (1024, )
MAX_SIZE_TRAIN: 2048
IMS_PER_BATCH: 8
SOLVER:
  MAX_ITER: 90000
CROP:
    ENABLED: False
NUM_WORKERS: 4 # this is the fastest in my case
```

Training time for base implementation: ~25 hours
Training time for detectron2 implementation with modified config: ~52 hours
Training time for detectron2 implementation with `configs/Cityscapes-PanopticSegmentation/panoptic_deeplab_R_52_os16_mg124_poly_90k_bs32_crop_512_1024.yaml`: ~55 hours

I do not observe any speedup by changing OS16 to OS32 in detectron2 implementation:
 ```
 RESNETS:
      RES5_DILATION: 1
```

I would like to check that this is the normal behaviour and that training in detectron2 takes much long, even twice as long as the base implementation. If this is the case, why is training in detectron2 so slow compared to the base implementation?
